chore(ci): update docker installer

diff --git a/.azure/docker.macos.yml b/.azure/docker.macos.yml
--- a/.azure/docker.macos.yml
+++ b/.azure/docker.macos.yml
@@ -1,11 +1,24 @@
 # https://github.com/Microsoft/azure-pipelines-image-generation/issues/738
 steps:
   - script: |
-      brew cask install https://raw.githubusercontent.com/Homebrew/homebrew-cask/b8c67034bd78f9585b1316564f223b97055bc0dc/Casks/docker.rb
+      retries=0
+      brew cask install https://raw.githubusercontent.com/Homebrew/homebrew-cask/8ce4e89d10716666743b28c5a46cd54af59a9cc2/Casks/docker.rb
       sudo /Applications/Docker.app/Contents/MacOS/Docker --quit-after-install --unattended
       /Applications/Docker.app/Contents/MacOS/Docker --unattended &
       while ! docker info 2>/dev/null ; do
         sleep 5
-        echo "Waiting for docker service to be in the running state"
+        retries=`expr $retries + 1`
+        if pgrep -xq -- "Docker"; then
+            echo 'docker still running'
+        else
+            echo 'docker not running, restart'
+            /Applications/Docker.app/Contents/MacOS/Docker --unattended &
+        fi
+        if [ $retries -gt 30 ]; then
+            >&2 echo 'Failed to run docker'
+            exit 1
+        fi;
+
+        echo 'Waiting for docker service to be in the running state'
       done
     displayName: Install docker
