ci: revert test changes

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -267,7 +267,6 @@ jobs:
           key: prettier-cache-${{ hashFiles('pnpm-lock.yaml', 'package.json') }}-${{ github.run_id }}-${{ github.run_attempt }}
 
   lint-docs:
-    if: false
     needs:
       - setup-build
     runs-on: ubuntu-latest
@@ -302,7 +301,6 @@ jobs:
         run: pnpm markdown-lint
 
   lint-other:
-    if: false
     needs:
       - setup-build
     runs-on: ubuntu-latest
@@ -351,7 +349,6 @@ jobs:
         run: pnpm lint-other
 
   lint-actions:
-    if: false
     needs:
       - setup-build
     runs-on: ubuntu-latest
@@ -380,10 +377,9 @@ jobs:
   test:
     needs: [setup, prefetch]
 
-    if: false
-    # if: |
-    #   !(github.event.pull_request.draft == true &&
-    #     needs.setup.outputs.test-matrix-empty == 'true')
+    if: |
+      !(github.event.pull_request.draft == true &&
+        needs.setup.outputs.test-matrix-empty == 'true')
 
     name: ${{ matrix.name }}
 
@@ -553,7 +549,7 @@ jobs:
       - build-docs
     runs-on: ubuntu-latest
     timeout-minutes: 1
-    if: false # always()
+    if: always()
     steps:
       - name: Fail for failed or cancelled tests
         if: |
@@ -634,7 +630,7 @@ jobs:
       - setup-build
     runs-on: ubuntu-latest
     timeout-minutes: 15
-    if: true # github.event.pull_request.draft != true
+    if: github.event.pull_request.draft != true
     steps:
       - name: Checkout code
         uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
@@ -663,7 +659,7 @@ jobs:
       - build
     runs-on: ubuntu-latest
     timeout-minutes: 15
-    if: false # github.event_name != 'pull_request' || (github.event.pull_request.draft != true && contains(github.event.pull_request.labels.*.name, 'ci:fulltest'))
+    if: github.event_name != 'pull_request' || (github.event.pull_request.draft != true && contains(github.event.pull_request.labels.*.name, 'ci:fulltest'))
     steps:
       - run: df -h
 
@@ -710,7 +706,7 @@ jobs:
       - setup-build
     runs-on: ubuntu-latest
     timeout-minutes: 5
-    if: false # github.event.pull_request.draft != true
+    if: github.event.pull_request.draft != true
     steps:
       - name: Checkout code
         uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
@@ -759,7 +755,7 @@ jobs:
     runs-on: 'ubuntu-latest'
     timeout-minutes: 7
 
-    if: false # github.event.pull_request.draft != true
+    if: github.event.pull_request.draft != true
 
     steps:
       - name: Checkout code
@@ -792,19 +788,18 @@ jobs:
   release:
     needs:
       - setup-build
-      - build
-      # - build-docker
-      # - lint-oxlint
-      # - lint-prettier
-      # - lint-docs
-      # - lint-other
-      # - test-e2e
-      # - test-success
-      # - build-docs
-      # - codecov
-      # - coverage-threshold
+      - build-docker
+      - lint-oxlint
+      - lint-prettier
+      - lint-docs
+      - lint-other
+      - test-e2e
+      - test-success
+      - build-docs
+      - codecov
+      - coverage-threshold
 
-    # if: github.repository == 'renovatebot/renovate' && github.event_name != 'pull_request'
+    if: github.repository == 'renovatebot/renovate' && github.event_name != 'pull_request'
     runs-on: ubuntu-latest
     timeout-minutes: 60
     concurrency:
@@ -822,7 +817,6 @@ jobs:
     steps:
       # right at the start of the job, make sure we're not seeing another commit that's landed
       - name: Check for newer commits
-        if: false
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           GH_REPO: renovatebot/renovate
@@ -834,6 +828,7 @@ jobs:
           if [[ "$latest_sha" != "$EXPECTED_SHA" ]]; then
             echo "Newer commit detected on $REF_NAME ($latest_sha), cancelling release run"
             gh run cancel "$RUN_ID"
+            sleep 5
           fi
 
       - run: df -h
@@ -842,10 +837,10 @@ jobs:
         id: check
         run: |
           if [[ -e /dev/sdb1 ]]; then
-            echo "We're on old vm, running cleanup"
+            echo "::warning::We're on old vm, running cleanup"
             echo "do-cleanup=true" >> "$GITHUB_OUTPUT"
           else
-            echo "We're on new vm, no cleanup required"
+            echo "::notice::We're on new vm, no cleanup required"
             echo "do-cleanup=false" >> "$GITHUB_OUTPUT"
           fi
 
@@ -886,17 +881,6 @@ jobs:
         with:
           node-version: ${{ needs.setup-build.outputs.node-version }}
           os: ${{ runner.os }}
-
-      - name: Download dist
-        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
-        with:
-          name: renovate-dist
-          path: dist/
-
-      - name: Build docker
-        run: pnpm build:docker build --platform linux/amd64,linux/arm64 --tries=1
-        env:
-          LOG_LEVEL: debug
 
       - name: Install newer npm if needed
         run: |
@@ -939,6 +923,7 @@ jobs:
           if [[ "$latest_sha" != "$EXPECTED_SHA" ]]; then
             echo "Newer commit detected on $REF_NAME ($latest_sha), cancelling release run"
             gh run cancel "$RUN_ID"
+            sleep 5
           fi
 
       - name: semantic-release
