ci: reorder release steps (#44339)
* ci: reorder release steps

* ci: testing

* ci: only cleanup on old vm

* ci: fix reference

* ci: testing

* ci: fix condition

* ci: fixup

* ci: fixup

* ci: revert test changes

* ci: fixup

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -828,7 +828,44 @@ jobs:
           if [[ "$latest_sha" != "$EXPECTED_SHA" ]]; then
             echo "Newer commit detected on $REF_NAME ($latest_sha), cancelling release run"
             gh run cancel "$RUN_ID"
+            sleep 5
           fi
+
+      - run: df -h
+
+      - name: check for old vm with low disk space
+        id: check
+        run: |
+          if [[ -e /dev/sdb1 ]]; then
+            echo "::warning::We're on old vm, running cleanup"
+            echo "do-cleanup=true" >> "$GITHUB_OUTPUT"
+          else
+            echo "::notice::We're on new vm, no cleanup required"
+            echo "do-cleanup=false" >> "$GITHUB_OUTPUT"
+          fi
+
+      # Some runner vm's are smaller than others for unknown reasons
+      # https://github.com/orgs/community/discussions/199328
+      # To avoid disk space issues when performing a release, we can clear up some disk space ahead of time
+      - name: Free Disk Space
+        if: ${{ steps.check.outputs.do-cleanup == 'true' }}
+        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
+        with:
+          # we're likely already using some of the globally installed tools
+          tool-cache: false
+          # there are no images by default
+          docker-images: false
+          # but we're definitely not using these
+          android: true
+          dotnet: true
+          haskell: true
+          # there is no swap storage anymore
+          swap-storage: false
+
+          large-packages: true # breaks docker cross platform support
+
+      - run: df -h
+        if: ${{ steps.check.outputs.do-cleanup == 'true' }}
 
       - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
         with:
@@ -840,35 +877,14 @@ jobs:
       - name: Setup Docker
         uses: ./.github/actions/setup-docker
 
-      - run: df -h
-
-      # Some runner vm's are smaller than others for unknown reasons
-      # https://github.com/orgs/community/discussions/199328
-      # To avoid disk space issues when performing a release, we can clear up some disk space ahead of time
-      - name: Free Disk Space
-        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
-        with:
-          # we're likely already using some of the globally installed tools
-          tool-cache: false
-          # there are no images by default
-          docker-images: false
-          # but we're definitely not using these
-          android: true
-          dotnet: true
-          haskell: true
-          # and shouldn't be using swap storage
-          swap-storage: true
-
-      - run: df -h
-
       - name: Setup Node.js
         uses: ./.github/actions/setup-node
         with:
           node-version: ${{ needs.setup-build.outputs.node-version }}
           os: ${{ runner.os }}
 
-      - name: Install newer npm
-        run: npm install -g npm
+      - name: Install newer npm if needed
+        run: 'dpkg --compare-versions "$(npm -v)" lt 11.5.1 && (npm update -g npm; echo "updated npm to: $(npm -v)") || echo "npm is new enough: $(npm -v)"'
 
       - uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2
 
@@ -907,6 +923,7 @@ jobs:
           if [[ "$latest_sha" != "$EXPECTED_SHA" ]]; then
             echo "Newer commit detected on $REF_NAME ($latest_sha), cancelling release run"
             gh run cancel "$RUN_ID"
+            sleep 5
           fi
 
       - name: semantic-release
