ci: only cleanup on old vm

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -803,7 +803,7 @@ jobs:
       # - codecov
       # - coverage-threshold
 
-    if: true # github.repository == 'renovatebot/renovate' && github.event_name != 'pull_request'
+    # if: github.repository == 'renovatebot/renovate' && github.event_name != 'pull_request'
     runs-on: ubuntu-latest
     timeout-minutes: 60
     concurrency:
@@ -828,6 +828,7 @@ jobs:
           EXPECTED_SHA: ${{ github.sha }}
           RUN_ID: ${{ github.run_id }}
         run: |
+          set -ex;
           latest_sha=$(git ls-remote https://github.com/renovatebot/renovate "refs/heads/$REF_NAME" | cut -f1)
           if [[ "$latest_sha" != "$EXPECTED_SHA" ]]; then
             echo "Newer commit detected on $REF_NAME ($latest_sha), cancelling release run"
@@ -836,10 +837,23 @@ jobs:
 
       - run: df -h
 
+      - name: check for old vm with low disk space
+        id: check
+        run: |
+          set -ex;
+          if [[ -e /dev/sdb1 ]]; then
+            echo "We're on old vm, running cleanup"
+            echo "do-cleanup=true" >> "$GITHUB_OUTPUT"
+          else
+            echo "We're on new vm, no cleanup required"
+            echo "do-cleanup=false" >> "$GITHUB_OUTPUT"
+          fi
+
       # Some runner vm's are smaller than others for unknown reasons
       # https://github.com/orgs/community/discussions/199328
       # To avoid disk space issues when performing a release, we can clear up some disk space ahead of time
       - name: Free Disk Space
+        if: ${{ check.outputs.do-cleanup }}
         uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
         with:
           # we're likely already using some of the globally installed tools
